repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.57.2
    hooks:
      - id: swiftformat
-   repo: local
    hooks:
      - id: sort-localizable-xcstrings
        name: Sort Localizable.xcstrings
        entry: bash -c 'for file in "$@"; do jq --sort-keys . "$file" > "$file.tmp" && mv "$file.tmp" "$file"; done' --
        language: system
        files: 'Localizable\.xcstrings$'
        pass_filenames: true
